### ISSUE TITLE
CheckerResponse not used in TalkToActor.scala

### ISSUE THREAD

**Issue by juanrh** [SalmaKhater/akka-examples#1]
Hi, 

In `akka-examples/playing-with-actors/src/main/scala/TalkToActor.scala` the trait `CheckerResponse` is not used. It looks like `CheckerResponse` should extend `CheckerMsg`, and `BlackUser` and `WhiteUser` should extend `CheckerResponse`, and that this is a typo.

Nice course anyway!

**Comment by SalmaKhater** [comment]
yes, you're right. It's typo
